version: '3'

services: 

  node-app:
    build: 
      context: node
    container_name: node-app
    entrypoint: >
      sh -c "dockerize -wait tcp://node-db:3306 -timeout 20s chmod +x ./.docker/entrypoint.sh &&
             ./.docker/entrypoint.sh"
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "4000:4000"
    depends_on: 
       - node-db

  node-db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: node-db
    restart: always
    tty: true
    volumes: 
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  node-nginx:
    build: .docker/nginx
    container_name: node-nginx
    tty: true
    ports:
      - "8005:8000"
    networks:
      - node-network
    depends_on:
      - node-db

    

networks: 
  node-network:
    driver: bridge      